### ISSUE TITLE
Publish to npm repository after PR-1

### ISSUE THREAD

**Issue by smuda** [musically-ut/grunt-connect-delay#6]
It seems you have not published a new version to NPM after merging PR-1 in february.

Since updating grunt, every time I run "npm install" I get the following error message:
grunt-connect-delay@0.2.3 requires a peer of grunt@~0.4.1 but none was installed.

Please push a new version to the npm repository.

**Comment by musically-ut** [comment]
Oh gosh!

Sorry for not pushing it earlier. Thanks for bringing it to my notice.

**Comment by smuda** [comment]
Thank you for fixing the issue!
